service: sumoaws

provider:

  name: aws
  runtime: nodejs8.10
  profile: sumo
  region: eu-west-3
  memorySize: 128
  # 128 is the minimum

  environment:
    # sumodb.sumogames.de => Rikishi list : Active, By Highest rank desc
    SUMODB_HOST: "http://sumodb.sumogames.de"
    RIKISHIS_PATH: "/Rikishi.aspx?shikona=&heya=-1&shusshin=-1&b=-1&high=-1&hd=-1&entry=-1&intai=999999&sort=5"
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-RIKISHIS

  iamRoleStatements:
    - Effect: "Allow"
      Action:
      - "dynamodb:Query"
      - "dynamodb:Scan"
      - "dynamodb:GetItem"
      - "dynamodb:PutItem"
      - "dynamodb:UpdateItem"
      - "dynamodb:DeleteItem"
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: "Allow"
      Action:
      - "sns:*"
      Resource: "*"

custom:
  dev:
    deletion_policy: Delete
  prod:
    deletion_policy: Retain

functions:

  scraprikishis:
    handler: src/main/js/handlers/handlerrikishis.startscrap
    description: On schedule, will parse riskishis main list and emit a SNS for each Rikishi
    timeout: 30 # sec
    events:
      - cron(0 0 * * ? *) # mn 0, hour 0, any day of month, whatever the day, any year)

  scraprikishi:
    handler: src/main/js/handlers/handlerrikishi.scraprikishi
    description: When trigger by SNS message containing url, will scrap one rikishi and stores into DynamoDB
    events:
      - sns: scraprikishi

  list:
    handler: src/main/js/handlers/listrikishis.get
    events:
      - http:
          path: rikishis
          method: get
    cors: true

resources:
  Resources:
    RikishisDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: ${self:custom.${opt:stage, self:provider.stage}.deletion_policy}
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: N
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

package:
  exclude:
    - src/tests/**
    - .env