service: sumoaws

provider:

  name: aws
  runtime: nodejs8.10
  profile: sumo
  region: eu-west-3
  memorySize: 128
  # 128 is the minimum

  environment:
    # sumodb.sumogames.de => Rikishi list : Active, By Highest rank desc
    rikishishost: "http://sumodb.sumogames.de"
    rikishispath: "/Rikishi.aspx?shikona=&heya=-1&shusshin=-1&b=-1&high=-1&hd=-1&entry=-1&intai=999999&sort=5"

  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
      - "sns:*"

functions:

  scraprikishis:
    handler: src/main/js/handlers/handlerrikishis.startscrap
    description: On schedule, will parse riskishis main list and emit a SNS for each Rikishi
    timeout: 30 # sec
    events:
      - cron(0 0 * * ? *) # mn 0, hour 0, any day of month, whatever the day, any year)

  scraprikishi:
    handler: src/main/js/handlers/handlerrikishi.scraprikishi
    description: When trigger by SNS message containing url, will scrap one rikishi and stores into DynamoDB
    events:
      - sns: scraprikishi

package:
  exclude:
    - src/tests/**
    - .env